kpinetwork/frontend-prototype

infrastructure/cdn/variables.tf
infrastructure/variables.tf

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-94)

feat: KPI-94 change domains

---

src/service/companyReport.js
src/service/comparisonPeers.js
src/service/session.js
src/service/universeOverview.js

feat: KPI-53 add authorizer

---

.github/workflows/cd-demo-frontend.yml
.github/workflows/cd-prod-frontend.yml
src/App.jsx
src/awsConfig.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-91)

feat: KPI-91 add google authentication

---

.github/workflows/cd-demo-frontend.yml
.github/workflows/cd-prod-frontend.yml
src/components/BubbleChart.jsx
src/components/Card/CardKPI.jsx
src/components/Header.jsx
src/components/HeaderInformation.jsx
src/utils/sortSizeCohort.js
src/views/CompanyView/Components/CompanyCard.jsx
src/views/CompanyView/Components/SelectCompany.jsx
src/views/ComparisionView/ComparisionView.jsx

feat: KPI-95 changes in bubble label and landing page

---

package-lock.json
package.json
src/App.jsx
src/components/Header.jsx
src/views/AdminPanel/AdminPanelView.jsx
src/views/AdminPanel/CompaniesView.jsx
src/views/AdminPanel/Components/Companies/CompaniesTable.jsx
src/views/AdminPanel/Components/TabPanel.jsx
src/views/AdminPanel/Components/Users/UsersTable.jsx
src/views/AdminPanel/UsersView.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-96)

feat: KPI-96 admin panel skeleton

---

src/views/AdminPanel/CompaniesView.jsx
src/views/AdminPanel/Components/Companies/CompaniesTable.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-108)

feat: KPI-108 build companies tab skeleton

---

src/hooks/useCompanyPanel.jsx
src/service/companyPanel.js
src/views/CompanyPanelView/Components/CompaniesTable.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-112)

feat: KPI-112 integrate get companies endpoint in company panel

---

package-lock.json
src/hooks/useCompanyPanel.jsx
src/hooks/useCompanyPermissions.jsx
src/hooks/useUserDetails.jsx
src/service/changeCompanyPublicly.js
src/service/users.js
src/views/CompanyPanelView/Components/CompaniesTable.jsx
src/views/PermissionsView/PermissionsView.jsx
src/views/UserPanelView/Components/Tabs/PermissionsTab.jsx
src/views/UserPanelView/Components/UserCard.jsx
src/views/UserPanelView/Components/UsersTable.jsx
src/views/UserPanelView/UserDetailView.jsx
src/views/UserPanelView/UserTabs.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-109)

feat: KPI-109 Allow admin to mark data as public in company panel

---

src/App.jsx
src/components/Header.jsx
src/hooks/useIsAdmin.jsx
src/service/session.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-100)

feat: KPI-100 restrict access to administration panel and urls

---

src/hooks/useUserRole.jsx
src/service/users.js
src/views/UserPanelView/Components/Tabs/RolesTab.jsx
src/views/UserPanelView/UserTabs.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-110)

feat: KPI-110 change user role

---

README.md
src/App.jsx
src/components/Header.jsx
src/hooks/useCompanyReport.jsx
src/hooks/useComparisionPeers.jsx
src/views/CompanyView/CompanyView.jsx
src/views/ComparisonView/ComparisonView.jsx
src/views/UniverseView/UniverseView.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-115)

feat: KPI-115 move comparison vs peers

---

src/App.jsx
src/components/Header.jsx
src/context/appContext.jsx
src/hooks/useCompanyReport.jsx
src/hooks/useComparisionPeers.jsx
src/hooks/useIsAdmin.jsx
src/hooks/useUniverseOverview.jsx
src/views/DefaultView/ErrorView.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-100)

feat: KPI-100 add forbidden view

---

src/App.jsx
src/components/CustomSignUpComponent.jsx
src/views/CompanyView/Components/DescriptionCard.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-116)

feat: KPI-116 add password hint

---

package-lock.json
package.json
src/App.jsx
src/components/CustomSignUpComponent.jsx

feat: KPI-0 reset password change

---

src/components/BubbleChart.jsx
src/views/CompanyView/Components/CompanyCard.jsx

feat: KPI-X delete revenue value

---

package.json
src/components/Card/CardKPI.jsx
src/hooks/useComparisionPeers.jsx
src/service/comparisonPeers.js
src/views/ComparisonView/ComparisonView.jsx

feat: KPI-117 export comparison data option

---

src/views/ComparisonView/ComparisonView.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-146)

feat: KPI-146 format revenue value

---

src/views/CompanyView/Components/CompanyCard.jsx
src/views/ComparisonView/ComparisonView.jsx

fix: KPI-XX round values

---

src/views/ComparisonView/ComparisonView.jsx

fix: KPI-XX round value in comparison vs peers

---

src/hooks/useUsers.jsx
src/service/users.js
src/views/UserPanelView/Components/UsersTable.jsx
src/views/UserPanelView/UserPanelView.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-124)

feat: KPI-124 user pagination

---

src/hooks/useCompaniesToChange.jsx
src/hooks/useCompanyPanel.jsx
src/hooks/useCompanyPermissions.jsx
src/hooks/useCompanyReport.jsx
src/hooks/usePublicCompanies.jsx
src/service/company.js
src/service/companyPanel.js
src/views/CompanyPanelView/Components/CompaniesTable.jsx
src/views/CompanyView/CompanyView.jsx
src/views/PermissionsView/PermissionsView.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-123)

feat: KPI-123 apply pagination on company administration pane

---

src/views/UniverseView/Components/Cards/ExpectedGrowthRateAndMarginCard.jsx
src/views/UniverseView/Components/Cards/GrowthAndMarginCard.jsx
src/views/UniverseView/Components/Cards/RevenueAndEbitdaCard.jsx

feat: KPi-143 growth and margin

---

src/tests/manual_tests.md

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-134)

feat: KPI-134 add manual tests md file

---

package-lock.json
package.json
src/views/AdminPanel/AdminPanelContainer.jsx
src/views/UploadFileView/Components/DragAndDrop.jsx
src/views/UploadFileView/Components/PreviewTable.jsx
src/views/UploadFileView/Components/PreviewTable.test.jsx

feat: KPI-152 add csv file preview

---

src/components/CustomTooltip.jsx
src/components/Filter/Growth.jsx
src/components/Filter/Size.jsx
src/utils/tooltipTitles.js
src/views/ComparisonView/ComparisonView.jsx
tests/components/CustomTooltip.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-163)

feat: KPI-163 tooltips

---

src/views/UploadFileView/Components/PreviewTable.jsx
tests/components/CustomTooltip.test.jsx
tests/views/UploadFileView/Components/PreviewTable.test.jsx

fix: KPI-168 fix validation when empty values on metric textfields

---

src/components/Header.jsx
src/hooks/useCompanyDetails.jsx
src/service/companyDetails.js
src/views/CompanyDetailsPanelView/Components/CompanyTabs.jsx
src/views/CompanyDetailsPanelView/Components/Tabs/InvestmentForm.jsx
src/views/CompanyDetailsPanelView/Components/Tabs/InvestmentsTab.jsx
src/views/CompanyPanelView/Components/CompaniesTable.jsx
tests/hooks/useCompanyDetails.test.jsx
tests/service/companyDetails.test.js
tests/views/CompanyDetailsPanelView/CompanyDetailView.test.jsx
tests/views/CompanyDetailsPanelView/Components/CompanyTabs.test.jsx
tests/views/CompanyDetailsPanelView/Components/Tabs/InvestmentForm.test.jsx
tests/views/CompanyDetailsPanelView/Components/Tabs/InvestmentsTab.test.jsx
tests/views/CompanyPanelView/Components/CompaniesTable.test.jsx
tests/views/ComparisonView/ComparisonView.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-179)

feat: KPI-179 investment endpoint integration

---

.gitignore
package-lock.json
package.json
src/components/InvestmentYearSelector.jsx
src/components/PeerGroupTabs.jsx
src/components/YearSelector.jsx
src/hooks/useCalendarReport.jsx
src/hooks/useComparisionPeers.jsx
src/hooks/useInvestmentYearReport.jsx
src/service/investmentByYearReport.js
src/views/CompanyView/CompanyView.jsx
src/views/ComparisonView/ComparisonView.jsx
src/views/Reports/ByYearReport.jsx
src/views/UniverseView/UniverseView.jsx
tests/components/InvestmentYearSelector.test.jsx
tests/components/PeerGroupTabs.test.jsx
tests/components/YearSelector.test.jsx
tests/hooks/useCalendarReport.test.jsx
tests/hooks/useInvestmentYearReport.test.jsx
tests/service/investmentByYearReport.test.js
tests/views/ComparisonView/ComparisonView.test.jsx
tests/views/Reports/ByYearReport.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-177)

feat: KPI 177 investment by year report

---

package-lock.json
src/components/MetricSelector.jsx
src/components/PeerGroupTabs.jsx
src/hooks/useMetricReport.jsx
src/service/metricReport.js
src/utils/constants/Metrics.js
src/views/Reports/ByMetricReport.jsx
tests/hooks/useMetricReport.test.jsx
tests/service/byMetricReport.test.js
tests/views/Reports/ByMetricReport.test.js
tests/views/Reports/ByYearReport.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-183)

feat: KPI-183 create by metric report

---

src/components/Card/CardKPI.jsx
src/components/HeaderInformation.jsx
src/hooks/useCompanyReport.jsx
src/service/company.js
src/utils/constants/Metrics.js
src/views/CompanyView/CompanyView.jsx
src/views/CompanyView/Components/DescriptionCard.jsx
src/views/CompanyView/Components/SelectCompany.jsx
tests/components/Card/CardKPI.test.jsx
tests/components/Filter/Growth.test.jsx
tests/components/Filter/Investor.test.jsx
tests/components/Filter/Sectors.test.jsx
tests/components/Filter/Size.test.jsx
tests/components/Filter/Vertical.test.jsx
tests/components/HeaderInformation.test.jsx
tests/components/MetricSelector.test.jsx
tests/data/companies.js
tests/data/filters.js
tests/hooks/useCalendarReport.test.jsx
tests/hooks/useCompaniesPanelTable.test.jsx
tests/hooks/useCompanyReport.test.jsx
tests/service/company.test.js
tests/service/companyDetails.test.js
tests/service/companyReport.test.js
tests/views/CompanyView/CompanyView.test.jsx
tests/views/CompanyView/Components/DescriptionCard.test.jsx
tests/views/CompanyView/Components/ReportRuleGraph.test.jsx
tests/views/CompanyView/Components/SelectCompany.test.jsx
tests/views/ComparisonView/ComparisonView.test.jsx
tests/views/Reports/ByMetricReport.test.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-128)

feat: KPI-128 company report unit tests

---

src/hooks/useScenariosTable.jsx
src/service/companyDetails.js
src/views/CompanyDetailsPanelView/CompanyDetailView.jsx
src/views/CompanyDetailsPanelView/Components/Tabs/ScenarioForm.jsx
src/views/CompanyDetailsPanelView/Components/Tabs/ScenariosModal.jsx
src/views/CompanyDetailsPanelView/Components/Tabs/ScenariosTab.jsx
tests/hooks/useScenariosTable.test.jsx
tests/service/companyDetails.test.js
tests/views/CompanyDetailsPanelView/Components/Tabs/ScenariosModal.test.jsx
tests/views/CompanyDetailsPanelView/Components/Tabs/ScenariosTab.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-162)

feat: KPI-162 delete scenarios

---

tests/views/CompanyDetailsPanelView/Components/Tabs/ScenariosTab.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-162)

fix: KPI-162 fix error in delete scenarios unit test

---

src/App.jsx
src/components/Progress.jsx
src/hooks/useEditModify.jsx
src/service/editModifyData.js
src/utils/validateFile/getObjectToValidate.js
src/views/AdminPanel/AdminPanelContainer.jsx
src/views/EditModify/Components/EditContainer.jsx
src/views/EditModify/Components/EditOptions.jsx
src/views/EditModify/Components/EditTable.jsx
src/views/EditModify/Components/ModifyModal.jsx
src/views/EditModify/Components/tracker.jsx
src/views/EditModify/EditModifyView.jsx
src/views/UploadFileView/Components/InvalidFormatModal.jsx
tests/data/editModify.js
tests/hooks/useEditModify.test.jsx
tests/service/editModifyData.test.js
tests/views/EditModify/Components/EditContainer.test.jsx
tests/views/EditModify/Components/EditOptions.test.jsx
tests/views/EditModify/Components/EditTable.test.jsx
tests/views/EditModify/Components/ModifyModal.test.jsx
tests/views/EditModify/Components/tracker.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-160)

feat: KPI-160 edit modify feat

---

src/hooks/useCompanyDetails.jsx
src/service/companyDetails.js
src/views/CompanyDetailsPanelView/Components/CompanyDetailsCard.jsx
src/views/CompanyDetailsPanelView/Components/DeleteModal.jsx
tests/hooks/useCompanyDetails.test.jsx
tests/service/companyDetails.test.js
tests/views/CompanyDetailsPanelView/Components/CompanyDetailsCard.test.jsx
tests/views/CompanyDetailsPanelView/Components/DeleteModal.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-172)

feat: KPI-172 delete company integration

---

src/views/ComparisonView/ComparisonView.jsx
tests/views/ComparisonView/ComparisonView.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-173)
- [ x] Feature (Issue from an Active Sprint)
- [ x] Unit Test.
- [ x] Coverage.

feat: KPI-173 order columns by comparison

---

src/hooks/useEditModify.jsx
src/service/editModifyData.js
src/views/EditModify/Components/EditContainer.jsx
src/views/EditModify/Components/Filters/Selectors.jsx
tests/hooks/useEditModify.test.jsx
tests/service/editModifyData.test.js
tests/views/EditModify/Components/EditContainer.test.jsx
tests/views/EditModify/Components/Filters/Selectors.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-193)

feat: KPI-193 edit modify filters

---

src/views/ComparisonView/ComparisonView.jsx
src/views/UploadFileView/Components/InvalidFormatModal.jsx
tests/views/UploadFileView/Components/InvalidFormatModal.test.jsx

feat: KPI-173 flex container for sorting options

---

src/hooks/useEditModify.jsx
src/views/EditModify/Components/EditContainer.jsx
src/views/EditModify/Components/tracker.jsx
tests/views/EditModify/Components/EditContainer.test.jsx

feat: KPI-000 fix edit modify

---

src/hooks/useScenariosTable.jsx
src/service/metrics.js
src/views/CompanyDetailsPanelView/Components/Tabs/ScenarioForm.jsx
src/views/CompanyDetailsPanelView/Components/Tabs/ScenariosModal.jsx
src/views/CompanyDetailsPanelView/Components/Tabs/ScenariosTab.jsx
tests/hooks/useScenariosTable.test.jsx
tests/service/metrics.test.jsx
tests/views/CompanyDetailsPanelView/Components/Tabs/ScenariosForm.test.jsx
tests/views/CompanyDetailsPanelView/Components/Tabs/ScenariosTab.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-196)

feat: KPI-196 call metric names endpoint for forms

---

src/utils/constants/Metrics.js
src/views/ComparisonView/ComparisonView.jsx
tests/views/ComparisonView/ComparisonView.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-203)

feat: KPI 203 new metrics on peer group analysis reports

---

src/hooks/useDynamicReport.jsx
src/utils/constants/Metrics.js
src/views/ComparisonView/ComparisonView.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-203)

feat: KPI-203 hide gross profit metric

---

src/components/Filter/Growth.jsx
src/components/Filter/Investor.jsx
src/components/Filter/Sectors.jsx
src/components/Filter/Size.jsx
src/components/Filter/Vertical.jsx
src/components/Header.jsx
src/components/HeaderInformation.jsx
src/context/appContext.jsx
tests/components/HeaderInformation.test.jsx
tests/context/appContext.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-212)

feat: KPI-212 save users preferences

---

src/service/universeOverview.js
tests/data/universeOverview.js
tests/hooks/useUniverseOverview.test.jsx
tests/service/universeOverview.test.js
tests/utils/sortSizeCohort.test.js
tests/views/UniverseView/Components/Cards/CountBySizeCard.test.js
tests/views/UniverseView/Components/Cards/ExpectedGrowthRateAndMarginCard.test.js
tests/views/UniverseView/Components/Cards/GrowthAndMarginCard.test.js
tests/views/UniverseView/Components/Cards/KPIAveragesCard.test.js
tests/views/UniverseView/Components/Cards/RevenueAndEbitdaCard.test.js
tests/views/UniverseView/Components/RuleGraph.test.js
tests/views/UniverseView/UniverseView.test.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-130)

test: KPI-130 universe overview unit testing

---

src/views/CompanyPanelView/Components/CompaniesTable.jsx
src/views/ComparisonView/ComparisonView.jsx
src/views/EditModify/Components/EditTable.jsx
src/views/Reports/ByMetricReport.jsx
src/views/Reports/DynamicReport.jsx
src/views/UploadFileView/Components/PreviewTable.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-210)

feat: KPI-210 static table headers for user pages and reports

---

src/hooks/useCompaniesPanelTable.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-214)

feat: KPI-214 change the default value in companies table

---

src/hooks/useDynamicReport.jsx
src/utils/constants/Metrics.js
src/views/ComparisonView/ComparisonView.jsx

feat: KPI-203 show gross profit in reports

---

src/views/UploadFileView/Components/PreviewTable.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-210)

feat: KPI-210 change import data table size

---

src/views/UniverseView/Components/RuleGraph.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-212)
Temporal solution of a bug with rule of 40 and preferences

feat: KPI-212 temporal fix to render rule of 40

---

src/components/MetricSelector.jsx
src/hooks/useDynamicReport.jsx
src/service/dynamicReport.js
src/views/Reports/DynamicReport.jsx
tests/hooks/useDynamicReport.test.jsx
tests/service/dynamicReport.test.js
tests/views/Reports/DynamicReport.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-221)

feat: KPI-221 dynamic report multiple selections

---

src/hooks/useScenariosTable.jsx
src/service/companyDetails.js
src/views/CompanyDetailsPanelView/Components/Tabs/ScenariosTab.jsx
tests/service/companyDetails.test.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-218)

feat: KPI-218 scenarios sorting

---

jest.config.js
setup-jest.js
src/hooks/usePublicCompanies.jsx
src/hooks/useUsers.jsx
src/service/users.js
src/views/PermissionsView/PermissionsView.jsx
src/views/UserPanelView/Components/Tabs/PermissionsTab.jsx
src/views/UserPanelView/Components/UsersTable.jsx
tests/hooks/useCompanyPermissions.test.jsx
tests/hooks/usePublicCompanies.test.jsx
tests/hooks/useUserDetails.test.jsx
tests/hooks/useUserRole.test.jsx
tests/hooks/useUsers.test.jsx
tests/service/users.test.js
tests/views/PermissionsView/PermissionsView.test.jsx
tests/views/UserPanelView/Components/Tabs/PermissionsTab.test.jsx
tests/views/UserPanelView/Components/Tabs/RolesTab.test.jsx
tests/views/UserPanelView/Components/UserCard.test.jsx
tests/views/UserPanelView/Components/UsersTable.test.jsx
tests/views/UserPanelView/UserDetailView.test.jsx
tests/views/UserPanelView/UserTabs.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-126)

test: KPI-126 add tests for user tab in admin panel

---

src/hooks/useCalendarReport.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-244)

fix: KPI-244 fix download csv bug

---

src/hooks/useScenariosTable.jsx
src/utils/constants/Metrics.js
src/views/CompanyDetailsPanelView/Components/Tabs/ScenariosTab.jsx
src/views/CompanyPanelView/Components/CompaniesTable.jsx
src/views/ComparisonView/ComparisonView.jsx
tests/hooks/useScenariosTable.test.jsx
tests/views/ComparisonView/ComparisonView.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-241)

feat: KPI-241 new metrics in peer group analysis

---

src/hooks/useDynamicReport.jsx
src/views/Reports/ByYearReport.jsx
src/views/Reports/DynamicReport.jsx
tests/hooks/useDynamicReport.test.jsx
tests/views/Reports/ByYearReport.test.jsx
tests/views/Reports/DynamicReport.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-236)

feat: KPI-236 delete investment year report

---

src/components/MetricSelector.jsx
src/components/PeerGroupTabs.jsx
src/components/TwoMetricSelectors.jsx
src/hooks/useDynamicReport.jsx
src/hooks/useInvestmentDateReport.jsx
src/service/investmentDateReport.js
src/utils/constants/CompanyDescription.js
src/views/Reports/ByYearReport.jsx
src/views/Reports/DynamicReport.jsx
src/views/Reports/InvestmentReport.jsx
tests/components/TwoMetricSelectors.test.jsx
tests/hooks/useDynamicReport.test.jsx
tests/hooks/useInvestmentDateReport.test.jsx
tests/service/investmentDateReport.test.js
tests/views/Reports/ByYearReport.test.jsx
tests/views/Reports/DynamicReport.test.jsx
tests/views/Reports/InvestmentReport.test.js
tests/views/UniverseView/UniverseView.test.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-235)

feat: KPI-235 investment date report

---

src/views/Reports/InvestmentReport.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-235)

fix: KPI-235 fix static company header in investment report table

---

src/components/Header.jsx
src/context/appContext.jsx
src/utils/useLocalStorage.js
src/views/Reports/ByMetricReport.jsx
src/views/Reports/ByYearReport.jsx
src/views/Reports/DynamicReport.jsx
src/views/Reports/InvestmentReport.jsx
tests/hooks/useScenariosTable.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-232)

feat: KPI-232 save user preferences in report

---

src/utils/constants/Metrics.js
src/utils/tooltipTitles.js
src/views/ComparisonView/ComparisonView.jsx
src/views/Reports/DynamicReport.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-233)

feat: KPI-233 tooltips for new metrics and dynamic report

---

src/utils/constants/Metrics.js
src/views/ComparisonView/ComparisonView.jsx
tests/views/ComparisonView/ComparisonView.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-265)

feat: KPI-265 add metrics in peer group sept 21

---

src/views/UserPanelView/Components/UserGroupTabs.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-227)

refactor: KPI-227 change order of users tabs

---

src/utils/constants/Metrics.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-265)

fix: KPI-265 add missing base metrics

---

src/utils/constants/Metrics.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-265)

fix: KPI-265 re order metrics in metrics combo

---

src/hooks/useTagsSections.jsx
src/hooks/useTagsTable.jsx
src/service/tags.js
src/views/TagsView/Components/TagsSectionView.jsx
src/views/TagsView/Components/TagsTable.jsx
tests/hooks/useTagsSection.test.jsx
tests/hooks/useTagsTable.test.jsx
tests/service/tags.test.js
tests/views/TagsView/Components/TagsSectionView.test.jsx
tests/views/TagsView/Components/TagsTable.test.jsx
tests/views/TagsView/TagsView.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-277)

feat: KPI-277 get tags integration

---

src/hooks/useCompanyTags.jsx
src/views/CompanyDetailsPanelView/Components/Tabs/TagsTab.jsx
tests/hooks/useCompanyTags.test.jsx
tests/views/CompanyDetailsPanelView/Components/Tabs/TagsTab.test.jsx

feat: KPI-282 update tags by company integration

---

src/hooks/useMetricRanges.jsx
src/service/metricRanges.js
src/utils/constants/Metrics.js
src/views/RangesView/Components/MetricRangeForm.jsx
src/views/RangesView/Components/MetricRangeFormTable.jsx
src/views/RangesView/Components/RangeViewContainer.jsx
tests/hooks/useMetricRanges.test.jsx
tests/service/metricRanges.test.js
tests/views/RangesView/Components/MetricRangeForm.test.jsx
tests/views/RangesView/Components/MetricRangeFormTable.test.jsx
tests/views/RangesView/Components/RangeViewContainer.test.jsx
tests/views/RangesView/RangesView.test.jsx

feat: KPI-304 modify ranges form

---

src/hooks/useMetricRanges.jsx
src/service/metricRanges.js
src/views/RangesView/Components/MetricRangeForm.jsx
src/views/RangesView/Components/MetricRangeFormTable.jsx
src/views/RangesView/Components/RangeViewContainer.jsx
tests/data/ranges.js
tests/hooks/useMetricRanges.test.jsx
tests/service/metricRanges.test.js
tests/views/RangesView/Components/MetricRangeForm.test.jsx
tests/views/RangesView/Components/MetricRangeFormTable.test.jsx
tests/views/RangesView/Components/RangeViewContainer.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-299)

feat: KPI-299 modify ranges integration

---

src/views/UploadFileView/Components/PreviewModal.jsx
tests/views/RangesView/Components/RangeTableTracker.test.jsx

fix: KPI-00 change upload data message

---

src/components/PeerGroupTabs.jsx
src/views/CompanyDetailsPanelView/Components/CompanyTabs.jsx
src/views/UserPanelView/Components/UserGroupTabs.jsx
src/views/UserPanelView/UserPanelView.jsx
tests/views/CompanyDetailsPanelView/CompanyDetailView.test.jsx
tests/views/CompanyDetailsPanelView/Components/CompanyTabs.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-260)

feat: KPI-260 standarize tabs style

---

src/context/appContext.jsx
src/views/RangesView/Components/MetricRangeFormTable.jsx
src/views/UniverseView/Components/Cards/KPIAveragesCard.jsx
src/views/UniverseView/Components/RuleGraph.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-231)

fix: KPI-231 data not showed when saved preferences in universe overview

---

src/hooks/useTagsTable.jsx
src/views/TagsView/Components/TagsSectionView.jsx
src/views/TagsView/Components/TagsTable.jsx
tests/views/TagsView/Components/TagsSectionView.test.jsx
tests/views/TagsView/Components/TagsTable.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-306)

fix: KPI-306 reset state modify tags cancel

---

src/utils/sortSizeCohort.js
tests/data/universeOverview.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-231)

fix: KPI-231 fix save preferences widgets

---

src/hooks/useEditModify.jsx
src/utils/validateFile/getObjectToValidate.js
src/views/UploadFileView/Components/PreviewContainer.jsx
src/views/UploadFileView/Components/PreviewModal.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-208)

feat: KPI-208 add metrics validation in upload data section

---

README.md

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-228)

feat: KPI-228 update read me file

---

package-lock.json
src/components/Alert/BasicSnackBar.jsx
src/hooks/useCompanyDetails.jsx
src/hooks/useMetricRanges.jsx
src/hooks/useScenariosTable.jsx
src/hooks/useTagsTable.jsx
src/service/companyDetails.js
src/service/metricRanges.js
src/service/tags.js
src/utils/constants/tagsError.js
src/views/CompanyDetailsPanelView/Components/Tabs/InvestmentForm.jsx
src/views/CompanyDetailsPanelView/Components/Tabs/InvestmentsTab.jsx
src/views/CompanyDetailsPanelView/Components/Tabs/ScenarioForm.jsx
src/views/CompanyDetailsPanelView/Components/Tabs/ScenariosTab.jsx
src/views/RangesView/Components/RangeViewContainer.jsx
src/views/TagsView/Components/TagsSectionView.jsx
tests/components/Alert/BasicSnackBar.test.jsx
tests/hooks/useCompanyDetails.test.jsx
tests/hooks/useScenariosTable.test.jsx
tests/hooks/useTagsTable.test.jsx
tests/views/CompanyDetailsPanelView/Components/Tabs/InvestmentForm.test.jsx
tests/views/CompanyDetailsPanelView/Components/Tabs/InvestmentsTab.test.jsx
tests/views/CompanyDetailsPanelView/Components/Tabs/ScenariosForm.test.jsx
tests/views/CompanyDetailsPanelView/Components/Tabs/ScenariosTab.test.jsx
tests/views/RangesView/Components/RangeViewContainer.test.jsx
tests/views/TagsView/Components/TagsSectionView.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-249)

feat: KPI-249 show the errors in the frontend

---

src/utils/sortSizeCohort.js
src/views/UniverseView/Components/Cards/CountBySizeCard.jsx
src/views/UniverseView/Components/Cards/ExpectedGrowthRateAndMarginCard.jsx
src/views/UniverseView/Components/Cards/GrowthAndMarginCard.jsx
src/views/UniverseView/Components/Cards/RevenueAndEbitdaCard.jsx
tests/utils/sortSizeCohort.test.js

fix: KPI-324 order count by size cards

---

src/views/CompanyDetailsPanelView/Components/CompanyDetailsCard.jsx
src/views/CompanyPanelView/Components/CompaniesTable.jsx
src/views/CompanyView/Components/DescriptionCard.jsx
src/views/ComparisonView/ComparisonView.jsx
src/views/EditModify/Components/EditTable.jsx
src/views/EditModify/Components/Filters/Selectors.jsx
tests/views/CompanyPanelView/Components/CompaniesTable.test.jsx
tests/views/CompanyView/Components/DescriptionCard.test.jsx
tests/views/ComparisonView/ComparisonView.test.jsx
tests/views/EditModify/Components/EditTable.test.jsx
tests/views/EditModify/Components/Filters/Selectors.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-327)

feat: KPI-327 delete sector and vertical

---

src/components/PeerGroupTabs.jsx
src/hooks/useCalendarReport.jsx
src/views/ComparisonView/ComparisonView.jsx
src/views/Reports/ByYearReport.jsx
tests/views/ComparisonView/ComparisonView.test.jsx
tests/views/Reports/ByYearReport.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-325)

feat: KPI-325 static row averages in year report

---

src/views/ComparisonView/ComparisonView.jsx
tests/components/HeaderInformation.test.jsx
tests/views/Reports/ByMetricReport.test.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-325)

fix: KPI-325 static row average in year report

---

src/components/Filter/Filter.jsx
src/components/Filter/Size.jsx
tests/components/Filter/Size.test.jsx
tests/views/CompanyView/CompanyView.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-333)

fix: KPI-333 get ranges options from backend in filters

---

src/hooks/useMetricReport.jsx
src/views/Reports/ByMetricReport.jsx
tests/views/Reports/ByMetricReport.test.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-328)

feat: KPI-328 add static averages row in by metric report

---

src/hooks/useDynamicReport.jsx
src/views/Reports/DynamicReport.jsx
tests/views/Reports/DynamicReport.test.jsx

feat: KPI-329 add averages row in dynamic report table

---

src/views/EditModify/Components/EditModifyTableHandler.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-334)

fix: KPI-334 add period name in payload

---

src/views/UploadFileView/Components/PreviewContainer.jsx
src/views/UploadFileView/Components/PreviewTable.jsx
tests/service/companyDetails.test.js
tests/service/metricRanges.test.js
tests/service/tags.test.js
tests/views/CompanyDetailsPanelView/Components/Tabs/ScenariosTab.test.jsx
tests/views/UploadFileView/Components/PreviewTable.test.jsx

feat: KPI-316 import data quarters header

---

src/hooks/useScenariosTable.jsx
src/service/companyDetails.js
src/utils/constants/Metrics.js
src/views/CompanyDetailsPanelView/Components/Tabs/ScenarioForm.jsx
src/views/CompanyDetailsPanelView/Components/Tabs/ScenariosTab.jsx
tests/hooks/useScenariosTable.test.jsx
tests/service/companyDetails.test.js
tests/views/CompanyDetailsPanelView/Components/Tabs/ScenariosForm.test.jsx
tests/views/CompanyDetailsPanelView/Components/Tabs/ScenariosTab.test.jsx
tests/views/Reports/ByYearReport.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-313)

feat: KPI-313 add input for quarters in scenario form

---

src/utils/userFunctions.js
src/utils/validateFile/getObjectToValidate.js
src/views/UploadFileView/Components/PreviewContainer.jsx
src/views/UploadFileView/Components/PreviewModal.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-318)
Validate that periods are correct before sending the file to upload

feat: KPI-318 add validation for periods row in import data

---

src/views/ComparisonView/ComparisonView.jsx
src/views/Reports/ByYearReport.jsx
src/views/UserPanelView/Components/UsersTable.jsx
tests/views/Reports/ByYearReport.test.jsx

KPI-XX enhancements in app

---

src/utils/constants/Metrics.js
src/views/CompanyDetailsPanelView/Components/Tabs/ScenarioForm.jsx
src/views/CompanyDetailsPanelView/Components/Tabs/ScenariosTab.jsx
tests/views/CompanyDetailsPanelView/Components/Tabs/ScenariosForm.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-313)

fix: KPI-313 change period options label, and tooltip side

---

src/hooks/useEditModify.jsx
tests/hooks/useEditModify.test.jsx
tests/views/EditModify/Components/EditModifyTableHandler.test.jsx

feat: KPI-344 add periods row in edit modify table

---

src/hooks/useEditModify.jsx
src/views/EditModify/Components/EditModifyTable.jsx
src/views/EditModify/Components/EditModifyTableHandler.jsx
tests/hooks/useEditModify.test.jsx
tests/views/EditModify/Components/EditModifyTableHandler.test.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-323)

feat: KPI-323 edit modify change body with quarters and full year

---

src/components/PeerGroupTabs.jsx
src/components/PeriodSelector.jsx
src/components/QuartersMetricSelector.jsx
src/components/ScenarioSelector.jsx
src/components/TypeOfReportSelector.jsx
src/components/YearSelector.jsx
src/hooks/useQuartersReport.jsx
src/service/quartersReport.js
src/utils/constants/Metrics.js
src/utils/constants/QuartersReportOptions.js
src/utils/fakeResponse.js
src/views/ComparisonView/ComparisonView.jsx
src/views/Reports/QuartersReport.jsx
tests/hooks/useQuartersReport.test.jsx
tests/service/QuartersReport.test.js
tests/utils/QuartersReportMock.js
tests/views/Reports/QuartersReport.test.jsx
tests/views/UniverseView/UniverseView.test.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-341)

feat: KPI-341 add quarters report view

---

src/utils/constants/QuartersReportOptions.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-340)

fix:KPI-340 fix quarters report view

---

src/utils/constants/QuartersReportOptions.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-347)

feat: KPI-347 enable last twelve motnhs option

---

src/utils/constants/QuartersReportOptions.js

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-347)

release: KPI-347 quarters report - enable twelve last months option

---

src/views/ComparisonView/ComparisonView.jsx
src/views/EditModify/Components/EditModifyTable.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-349)

fix: KPI-349 fix styling to show years in edit modify table

---

src/utils/constants/QuartersReportOptions.js
src/views/ComparisonView/ComparisonView.jsx
src/views/EditModify/Components/EditModifyTable.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-349)

release: KPI-349 352 Fix edit modify column headers

---

src/views/EditModify/Components/EditModifyTable.jsx
src/views/Reports/QuartersReport.jsx

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-353)

feat: KPI-353 add format to ratio metrics

---

src/components/PeriodSelector.jsx
src/views/Reports/QuartersReport.jsx

fix: KPI-353 fix quarters report
